# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-05 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topology', '0004_auto_20200405_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediator',
            name='created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='mediator',
            name='updated',
            field=models.DateTimeField(),
        ),
    ]
