# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-06 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('topology', '0007_auto_20200405_2120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='name_de',
            new_name='title_de',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='name_en',
            new_name='title_en',
        ),
        migrations.RenameField(
            model_name='mediation',
            old_name='name_de',
            new_name='demand_de',
        ),
        migrations.RenameField(
            model_name='mediation',
            old_name='name_en',
            new_name='demand_en',
        ),
        migrations.RenameField(
            model_name='mediator',
            old_name='name_de',
            new_name='title_de',
        ),
        migrations.RenameField(
            model_name='mediator',
            old_name='name_en',
            new_name='title_en',
        ),
        migrations.RenameField(
            model_name='medium',
            old_name='name_de',
            new_name='title_de',
        ),
        migrations.RenameField(
            model_name='medium',
            old_name='name_en',
            new_name='title_en',
        ),
        migrations.RenameField(
            model_name='space',
            old_name='name_de',
            new_name='title_de',
        ),
        migrations.RenameField(
            model_name='space',
            old_name='name_en',
            new_name='title_en',
        ),
        migrations.RenameField(
            model_name='time',
            old_name='name_de',
            new_name='title_de',
        ),
        migrations.RenameField(
            model_name='time',
            old_name='name_en',
            new_name='title_en',
        ),
        migrations.RenameField(
            model_name='value',
            old_name='name_de',
            new_name='title_de',
        ),
        migrations.RenameField(
            model_name='value',
            old_name='name_en',
            new_name='title_en',
        ),
        migrations.AddField(
            model_name='mediation',
            name='response_de',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mediation',
            name='response_en',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mediator',
            name='location',
            field=location_field.models.plain.PlainLocationField(default='48.21071849058017,16.371345520019528', max_length=63),
        ),
    ]
