# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-06 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topology', '0010_auto_20200406_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediator',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mediator',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
