# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-19 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topology', '0011_auto_20200406_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediator',
            name='bearing',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='mediator',
            name='pitch',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='mediator',
            name='zoom',
            field=models.FloatField(blank=True, default=18, null=True),
        ),
    ]
