# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-08-02 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topology', '0012_auto_20200519_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediator',
            name='moment_de',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mediator',
            name='moment_en',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mediator',
            name='place_de',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mediator',
            name='place_en',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
