# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0006_auto_20171110_1524'),
        ('topography', '0009_remove_event_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='information',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='information.Information'),
        ),
    ]
