# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-25 17:40
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('topography', '0014_auto_20181128_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='abstract_de',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='abstract_en',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
