# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-05 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topography', '0016_auto_20200405_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='updated',
            field=models.DateTimeField(),
        ),
    ]
