# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-05 16:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('information', '0022_auto_20181225_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_de', models.TextField()),
                ('name_en', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mediation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_de', models.TextField()),
                ('name_en', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mediator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_de', models.TextField()),
                ('name_en', models.TextField()),
                ('abstract_de', tinymce.models.HTMLField(blank=True, null=True)),
                ('abstract_en', tinymce.models.HTMLField(blank=True, null=True)),
                ('information', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='information.Information')),
            ],
        ),
        migrations.CreateModel(
            name='Medium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_de', models.TextField()),
                ('name_en', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='topology.Mediator')),
            ],
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_de', models.TextField()),
                ('name_en', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_de', models.TextField()),
                ('name_en', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_de', models.TextField()),
                ('name_en', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='relation',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topology.Space'),
        ),
        migrations.AddField(
            model_name='relation',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='topology.Mediator'),
        ),
        migrations.AddField(
            model_name='relation',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topology.Time'),
        ),
        migrations.AddField(
            model_name='relation',
            name='value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topology.Value'),
        ),
        migrations.AddField(
            model_name='mediator',
            name='medium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topology.Medium'),
        ),
        migrations.AddField(
            model_name='mediation',
            name='relations',
            field=models.ManyToManyField(related_name='mediations', to='topology.Relation'),
        ),
        migrations.AddField(
            model_name='experience',
            name='relations',
            field=models.ManyToManyField(related_name='experiences', to='topology.Relation'),
        ),
    ]
