# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-05 17:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('topology', '0003_auto_20200405_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediator',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mediator',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
