# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-05 18:08
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('topology', '0005_auto_20200405_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediator',
            name='keywords',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
