# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-08-02 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('topology', '0013_auto_20200802_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediator',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
