# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='caption_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audio',
            name='caption_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='sub_title_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='sub_title_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='title_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='title_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='sub_title_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='sub_title_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='caption_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='caption_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='content_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='content_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='content_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='content_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='caption_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='caption_en',
            field=models.TextField(blank=True, null=True),
        ),
    ]
