# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 19:47
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0003_auto_20171101_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='content_de',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='content_en',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
