# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('topography', '0009_remove_event_information'),
        ('information', '0004_auto_20171107_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_de', models.TextField(blank=True, null=True)),
                ('title_en', models.TextField(blank=True, null=True)),
                ('content_de', tinymce.models.HTMLField(blank=True, null=True)),
                ('content_en', tinymce.models.HTMLField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='entity',
            name='container',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='content_type',
        ),
        migrations.DeleteModel(
            name='Quote',
        ),
        migrations.DeleteModel(
            name='Text',
        ),
        migrations.DeleteModel(
            name='Container',
        ),
        migrations.DeleteModel(
            name='Entity',
        ),
    ]
