# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-29 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0009_auto_20171110_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
