# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-17 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0012_auto_20181117_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='media_audios',
            field=models.ManyToManyField(blank=True, to='information.Audio'),
        ),
        migrations.AddField(
            model_name='information',
            name='media_galleries',
            field=models.ManyToManyField(blank=True, to='information.Gallery'),
        ),
        migrations.AddField(
            model_name='information',
            name='media_images',
            field=models.ManyToManyField(blank=True, to='information.Image'),
        ),
        migrations.AddField(
            model_name='information',
            name='media_videos',
            field=models.ManyToManyField(blank=True, to='information.Video'),
        ),
    ]
