# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-27 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0013_auto_20181117_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='abstract_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='abstract_en',
            field=models.TextField(blank=True, null=True),
        ),
    ]
