# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-27 23:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0014_auto_20181127_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='abstract_de',
        ),
        migrations.RemoveField(
            model_name='information',
            name='abstract_en',
        ),
    ]
