# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-06 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0016_video_stream_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='stream_id',
            field=models.CharField(help_text="For example: 'c47c9323f8628c10527cdd9748173e5acc4d8c9c'", max_length=128),
        ),
    ]
