# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 19:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_auto_20171008_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='sub_title_de',
        ),
        migrations.RemoveField(
            model_name='container',
            name='sub_title_en',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='sub_title_de',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='sub_title_en',
        ),
    ]
