# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 15:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0008_auto_20171110_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='information',
            old_name='media_audio',
            new_name='media_audios',
        ),
        migrations.RenameField(
            model_name='information',
            old_name='media_gallery',
            new_name='media_galleries',
        ),
        migrations.RenameField(
            model_name='information',
            old_name='media_image',
            new_name='media_images',
        ),
        migrations.RenameField(
            model_name='information',
            old_name='media_video',
            new_name='media_videos',
        ),
    ]
