# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-17 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0011_remove_information_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='url',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='title_de',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='image',
            name='url',
        ),
        migrations.RemoveField(
            model_name='information',
            name='media_audios',
        ),
        migrations.RemoveField(
            model_name='information',
            name='media_galleries',
        ),
        migrations.RemoveField(
            model_name='information',
            name='media_images',
        ),
        migrations.RemoveField(
            model_name='information',
            name='media_videos',
        ),
        migrations.RemoveField(
            model_name='video',
            name='url',
        ),
        migrations.AddField(
            model_name='audio',
            name='phaidra_id',
            field=models.CharField(default='', help_text="For example: 'o:906180'", max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='phaidra_id',
            field=models.CharField(default='', help_text="For example: 'o:906180'", max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='phaidra_id',
            field=models.CharField(default='', help_text="For example: 'o:906180'", max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='information',
            name='content_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='content_en',
            field=models.TextField(blank=True, null=True),
        ),
    ]
