# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-25 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0020_auto_20181225_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='thumbnail',
            field=models.ImageField(default='test.png', upload_to='audio_thumbnails/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(default='test.png', upload_to='video_thumbnails/'),
            preserve_default=False,
        ),
    ]
