# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-25 20:04
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0021_auto_20181225_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='caption_de',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audio',
            name='caption_en',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='caption_de',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='caption_en',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='caption_de',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='caption_en',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
