# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-03-12 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0022_auto_20181225_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
