# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 20:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topography', '0003_auto_20171027_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='next_event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='previous_event', to='topography.Event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='title_de',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='title_en',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
