# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-17 14:21
from __future__ import unicode_literals

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('topography', '0010_event_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=location_field.models.plain.PlainLocationField(default=1, max_length=63),
            preserve_default=False,
        ),
    ]
