# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-17 15:23
from __future__ import unicode_literals

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('topography', '0012_auto_20181117_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=location_field.models.plain.PlainLocationField(default='48.21071849058017,16.371345520019528', max_length=63),
        ),
    ]
