# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-06 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('main', '0002_page_information'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusmediusTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('title_de', models.TextField()),
                ('title_en', models.TextField()),
            ],
            options={
                'verbose_name': 'keyword',
            },
        ),
        migrations.CreateModel(
            name='CampusmediusTaggedItemBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField(db_index=True, verbose_name='Object id')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_campusmediustaggeditembase_tagged_items', to='contenttypes.ContentType', verbose_name='Content type')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_campusmediustaggeditembase_items', to='main.CampusmediusTag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
