# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-06 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_campusmediustag_campusmediustaggeditembase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campusmediustag',
            name='title_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campusmediustag',
            name='title_en',
            field=models.TextField(blank=True, null=True),
        ),
    ]
