# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-06 17:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200406_1900'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campusmediustag',
            options={},
        ),
    ]
