# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-06 17:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200406_1913'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campusmediustag',
            options={'verbose_name': 'keyword'},
        ),
    ]
