# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-01-13 13:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200406_1929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='content_de',
            new_name='mobile_abstract_de',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='content_en',
            new_name='mobile_abstract_en',
        ),
    ]
