# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-02-21 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210113_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
