# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-02-25 15:02
from __future__ import unicode_literals

from django.db import migrations
import taggit_autosuggest.managers


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210221_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='keywords',
            field=taggit_autosuggest.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='main.CampusmediusTaggedItemBase', to='main.CampusmediusTag', verbose_name='keywords'),
        ),
    ]
